- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org
  logoColor: FFFFFF
  color: 007ACC

- name: JavaScript
  logo: javascript
  logoColor: FFFFFF
  color: F7DF1E
  url: https://nodejs.org

- name: Java
  logo: java
  url: https://www.java.com
  logoColor: FFFFFF
  color: 00ADD8

- name: Python
  logo: python
  url: https://python.org
  logoColor: FFFFFF
  color: 3776AB
  projects:
    - url: https://github.com/cjdenio/contributor_list